"""Historical crisis/recession events (PRD Section 41) for the simplified backtesting page."""

from __future__ import annotations

from datetime import date
from typing import Any

CRISIS_EVENTS: list[dict[str, Any]] = [
    dict(name="1973-74 Bear Market / Oil Crisis", event_start=date(1973, 1, 11), event_end=date(1974, 10, 3),
         peak_to_trough_drawdown=-48.2, recession_start=date(1973, 11, 1), recession_end=date(1975, 3, 1),
         description="Oil embargo, stagflation, and a severe bear market.",
         name_zh="1973-74年熊市/石油危机", description_zh="石油禁运、滞胀与严重熊市。"),
    dict(name="1980 Recession", event_start=date(1980, 1, 1), event_end=date(1980, 7, 1),
         peak_to_trough_drawdown=-17.1, recession_start=date(1980, 1, 1), recession_end=date(1980, 7, 1),
         description="Short, sharp recession amid Volcker's initial rate-hiking cycle.",
         name_zh="1980年经济衰退", description_zh="沃尔克首轮加息周期中出现的短暂而剧烈的衰退。"),
    dict(name="1981-82 Recession", event_start=date(1981, 7, 1), event_end=date(1982, 11, 1),
         peak_to_trough_drawdown=-27.1, recession_start=date(1981, 7, 1), recession_end=date(1982, 11, 1),
         description="Volcker disinflation recession; double-digit unemployment.",
         name_zh="1981-82年经济衰退", description_zh="沃尔克反通胀衰退；失业率达两位数。"),
    dict(name="1987 Crash", event_start=date(1987, 8, 25), event_end=date(1987, 12, 4),
         peak_to_trough_drawdown=-33.5, recession_start=None, recession_end=None,
         description="Black Monday portfolio-insurance-driven crash, no accompanying recession.",
         name_zh="1987年股灾", description_zh="由投资组合保险策略引发的“黑色星期一”崩盘，未伴随经济衰退。"),
    dict(name="1990 Recession", event_start=date(1990, 7, 16), event_end=date(1990, 10, 11),
         peak_to_trough_drawdown=-19.9, recession_start=date(1990, 7, 1), recession_end=date(1991, 3, 1),
         description="Gulf War oil shock and S&L crisis aftermath.",
         name_zh="1990年经济衰退", description_zh="海湾战争石油冲击与储贷危机余波。"),
    dict(name="1997 Asian Financial Crisis", event_start=date(1997, 7, 2), event_end=date(1997, 10, 27),
         peak_to_trough_drawdown=-13.7, recession_start=None, recession_end=None,
         description="Asian currency crisis spillover into global markets.",
         name_zh="1997年亚洲金融危机", description_zh="亚洲货币危机波及全球市场。"),
    dict(name="1998 LTCM / Russia", event_start=date(1998, 7, 17), event_end=date(1998, 10, 8),
         peak_to_trough_drawdown=-19.3, recession_start=None, recession_end=None,
         description="Russian default and LTCM collapse triggered a global liquidity scare.",
         name_zh="1998年LTCM/俄罗斯危机", description_zh="俄罗斯债务违约与长期资本管理公司（LTCM）倒闭引发全球流动性恐慌。"),
    dict(name="2000-02 Dot-Com Bear Market", event_start=date(2000, 3, 24), event_end=date(2002, 10, 9),
         peak_to_trough_drawdown=-49.1, recession_start=date(2001, 3, 1), recession_end=date(2001, 11, 1),
         description="Tech-bubble collapse and a mild recession.",
         name_zh="2000-02年互联网泡沫熊市", description_zh="科技泡沫破裂与温和衰退。"),
    dict(name="2007-09 Global Financial Crisis", event_start=date(2007, 10, 9), event_end=date(2009, 3, 9),
         peak_to_trough_drawdown=-56.8, recession_start=date(2007, 12, 1), recession_end=date(2009, 6, 1),
         description="Subprime/credit crisis; the primary reference case for this dashboard's credit/liquidity focus.",
         name_zh="2007-09年全球金融危机", description_zh="次贷/信贷危机；是本仪表盘信贷与流动性关注重点的主要参照案例。"),
    dict(name="2011 Debt Ceiling / Euro Stress", event_start=date(2011, 4, 29), event_end=date(2011, 10, 3),
         peak_to_trough_drawdown=-19.4, recession_start=None, recession_end=None,
         description="U.S. debt-ceiling standoff and European sovereign-debt crisis.",
         name_zh="2011年债务上限/欧债危机", description_zh="美国债务上限僵局与欧洲主权债务危机。"),
    dict(name="2015-16 Growth/Commodity Selloff", event_start=date(2015, 5, 21), event_end=date(2016, 2, 11),
         peak_to_trough_drawdown=-14.2, recession_start=None, recession_end=None,
         description="China growth scare and commodity/oil price collapse.",
         name_zh="2015-16年增长/大宗商品抛售", description_zh="中国增长担忧与大宗商品/油价暴跌。"),
    dict(name="2018 Q4 Correction", event_start=date(2018, 9, 20), event_end=date(2018, 12, 24),
         peak_to_trough_drawdown=-19.8, recession_start=None, recession_end=None,
         description="Fed tightening fears and trade-war escalation.",
         name_zh="2018年第四季度回调", description_zh="美联储紧缩担忧与贸易战升级。"),
    dict(name="2020 COVID Crash", event_start=date(2020, 2, 19), event_end=date(2020, 3, 23),
         peak_to_trough_drawdown=-33.9, recession_start=date(2020, 2, 1), recession_end=date(2020, 4, 1),
         description="Fastest bear market in history; extreme funding stress met with unprecedented Fed intervention.",
         name_zh="2020年新冠疫情崩盘", description_zh="史上最快熊市；极端融资压力遭遇美联储史无前例的干预。"),
    dict(name="2022 Inflation/Rates Bear Market", event_start=date(2022, 1, 3), event_end=date(2022, 10, 12),
         peak_to_trough_drawdown=-25.4, recession_start=None, recession_end=None,
         description="Fastest Fed hiking cycle in decades to combat multi-decade-high inflation.",
         name_zh="2022年通胀/利率熊市", description_zh="美联储数十年来最快加息周期，以应对数十年来最高通胀。"),
]
