"""Indicator registry seed data.

~110 indicators spanning every PRD category (Sections 8-22, 27-29), prioritizing the 30
"critical dashboard" indicators from Section 55. Each entry carries both the real
series_identifier for its connector (used when DATA_SOURCE_MODE=live) and mock generation
params (base/vol/drift/floor/ceiling) used when live data isn't available. Extending the
universe later is purely a matter of adding rows here (Section 58's constraint: adding an
indicator is a config operation, not a frontend change).

`guide` is indicator-specific "how to read it" text (what rising vs. falling means for
equities) - deliberately NOT a generic per-polarity template, since a handful of buckets
("higher is healthier") reads as boilerplate once you've seen it on the third card. See
health_score.py's reading_guide() for the polarity-generic fallback used only if `guide` is
left blank.
"""

from __future__ import annotations

from typing import Any


def I(
    slug: str,
    name: str,
    category: str,
    subcategory: str,
    cluster: str,
    connector: str,
    series: str,
    freq: str,
    units: str,
    polarity: str,
    lead_lag: str = "coincident",
    crisis: str = "medium",
    critical: bool = False,
    base: float = 1.0,
    vol: float = 0.05,
    drift: float = 0.0,
    floor: float | None = None,
    ceiling: float | None = None,
    cycle: float = 0.0,
    info: str = "",
    guide: str = "",
    source_name: str = "FRED",
    source_url: str = "",
    green: float = 70.0,
    yellow: float = 40.0,
) -> dict[str, Any]:
    return dict(
        slug=slug,
        name=name,
        category=category,
        subcategory=subcategory,
        cluster=cluster,
        connector=connector,
        series=series,
        frequency=freq,
        units=units,
        health_polarity=polarity,
        lead_lag=lead_lag,
        crisis_relevance=crisis,
        is_critical=critical,
        mock=dict(base=base, vol=vol, drift=drift, floor=floor, ceiling=ceiling, cycle_amplitude=cycle),
        info_text=info,
        reading_guide=guide,
        source_name=source_name,
        source_url=source_url,
        green_threshold=green,
        yellow_threshold=yellow,
    )


INDICATORS: list[dict[str, Any]] = [
    # ---- Credit / risk appetite (Section 10) ----
    I("hy-oas", "ICE BofA U.S. High Yield OAS", "credit_risk_appetite", "credit", "credit", "fred", "BAMLH0A0HYM2", "daily", "percent", "lower_is_healthy",
      lead_lag="leading", crisis="high", critical=True, base=3.8, vol=0.06, floor=2.0, ceiling=12.0,
      info="Spread of high-yield corporate bonds over Treasuries. Widens when credit investors demand more compensation for risk - a classic early stress signal that often leads equity weakness.",
      guide="Rising is unfavorable for equities - investors demanding more compensation for risk signals credit stress that often leads equity weakness. Falling is favorable - easier high-yield funding conditions support risk appetite.",
      green=60, yellow=15),
    I("ig-oas", "ICE BofA U.S. Corporate IG OAS", "credit_risk_appetite", "credit", "credit", "fred", "BAMLC0A0CM", "daily", "percent", "lower_is_healthy",
      lead_lag="leading", crisis="high", critical=True, base=1.1, vol=0.03, floor=0.5, ceiling=4.0,
      info="Investment-grade corporate spread over Treasuries. Less volatile than high-yield but a widening trend signals broad-based funding-cost stress even for higher-quality borrowers.",
      guide="Rising is unfavorable - even high-quality borrowers facing wider spreads signals broad funding-cost stress. Falling is favorable - cheaper investment-grade funding supports corporate activity and valuations."),
    I("baa-10y-spread", "Baa - 10Y Treasury Spread", "credit_risk_appetite", "credit", "credit", "fred", "BAA10Y", "daily", "percent", "lower_is_healthy",
      lead_lag="leading", crisis="medium", base=2.0, vol=0.04, floor=1.0, ceiling=6.0,
      info="Spread between Moody's Baa corporate bonds and the 10Y Treasury. A long-running corporate-credit-stress series with data back to the 1980s.",
      guide="Rising is unfavorable - a wider Baa spread signals corporate credit stress building. Falling is favorable - narrowing spreads reflect easier credit conditions."),
    I("cp-spread", "Commercial Paper Spread", "credit_risk_appetite", "credit", "credit", "fred", "CPFF", "daily", "percent", "lower_is_healthy",
      crisis="high", base=0.3, vol=0.03, floor=0.0, ceiling=3.0,
      info="Spread on short-term corporate commercial paper. A sharp widening here was a hallmark of both 2008 and the March 2020 funding freeze.",
      guide="Rising is unfavorable - commercial paper is short-term corporate funding; a widening spread here signaled funding freezes in both 2008 and March 2020. Falling is favorable - normal short-term funding conditions."),
    I("nfci", "Chicago Fed NFCI", "credit_risk_appetite", "financial_conditions", "credit", "fred", "NFCI", "weekly", "index", "lower_is_healthy",
      lead_lag="leading", crisis="high", critical=True, base=-0.3, vol=0.08, floor=-1.0, ceiling=3.0,
      info="Composite index of financial conditions (money markets, debt/equity markets, banking system). Zero = historical average; positive = tighter than average conditions.",
      guide="Rising above zero is unfavorable - tighter-than-average financial conditions historically precede slower growth and equity weakness. Falling below zero is favorable - looser conditions support risk assets."),
    I("stlfsi", "St. Louis Fed Financial Stress Index", "credit_risk_appetite", "financial_conditions", "credit", "fred", "STLFSI4", "weekly", "index", "lower_is_healthy",
      lead_lag="leading", crisis="high", critical=True, base=-0.5, vol=0.15, floor=-2.0, ceiling=5.0,
      info="Composite of 18 weekly financial series. Zero = normal stress; each unit above zero is roughly one standard deviation of stress above average.",
      guide="Rising is unfavorable - each point above zero is roughly one standard deviation of added financial stress. Falling toward or below zero is favorable - normalizing conditions."),
    I("hyg-lqd-rel", "HYG vs LQD Relative Performance", "credit_risk_appetite", "credit_etf", "credit", "fred", "N/A_HYGLQD", "daily", "ratio", "higher_is_healthy",
      lead_lag="leading", crisis="medium", base=1.0, vol=0.01, floor=0.6, ceiling=1.4,
      info="Ratio of high-yield to investment-grade bond ETF prices. Falling means credit investors are rotating away from risk before it always shows up in equities.",
      guide="Rising is favorable - high-yield bonds outperforming investment-grade signals credit investors are comfortable taking risk. Falling is unfavorable - credit investors rotating toward safety, often ahead of equity weakness."),
    I("leveraged-loan-proxy", "Leveraged Loan Stress Proxy", "credit_risk_appetite", "credit", "credit", "fred", "BAMLHYH0A0HYM2TRIV", "daily", "index", "higher_is_healthy",
      crisis="medium", base=100.0, vol=1.5, floor=60.0,
      info="Free-data proxy for leveraged-loan market stress using high-yield total-return trends, since detailed loan-level data is a paid dataset excluded from MVP.",
      guide="Rising is favorable - improving high-yield total returns proxy easier leveraged-loan market conditions. Falling is unfavorable - a proxy for tightening loan-market stress."),
    I("excess-bond-premium", "Excess Bond Premium (proxy)", "credit_risk_appetite", "credit", "credit", "fred", "N/A_EBP", "monthly", "percent", "lower_is_healthy",
      lead_lag="leading", crisis="high", base=0.2, vol=0.05, floor=-1.0, ceiling=3.0,
      info="Proxy for the Fed's excess bond premium - the part of credit spreads not explained by default risk, historically a strong leading recession indicator.",
      guide="Rising is unfavorable - credit stress beyond what default risk alone explains, historically a strong recession lead indicator. Falling is favorable - spreads more in line with fundamentals."),

    # ---- Banking / credit creation (Section 18) ----
    I("sloos-ci-standards", "SLOOS: C&I Lending Standards", "banking_credit_creation", "banking", "banking", "fred", "DRTSCILM", "quarterly", "pct_net_tightening", "lower_is_healthy",
      lead_lag="leading", crisis="high", critical=True, base=5.0, vol=8.0, floor=-40.0, ceiling=80.0,
      info="Net % of banks tightening C&I lending standards (Senior Loan Officer Opinion Survey). Rising values mean banks are pulling back credit before it shows up in growth data.",
      guide="Rising is unfavorable - more banks tightening standards signals credit is becoming harder to get, typically ahead of slower growth. Falling is favorable - banks easing standards supports credit creation."),
    I("bank-loan-growth", "Commercial Bank Loan Growth", "banking_credit_creation", "banking", "banking", "fred", "TOTLL", "weekly", "pct_yoy", "higher_is_healthy",
      crisis="medium", base=5.0, vol=1.0, floor=-10.0, ceiling=15.0,
      info="Year-over-year growth in total bank loans and leases. Contraction signals a broad credit-creation slowdown that historically precedes weaker growth.",
      guide="Rising is favorable - accelerating loan growth signals healthy credit creation supporting the economy. Falling or negative is unfavorable - a broad credit-creation slowdown that historically precedes weaker growth."),
    I("ci-loan-growth", "C&I Loan Growth", "banking_credit_creation", "banking", "banking", "fred", "BUSLOANS", "monthly", "pct_yoy", "higher_is_healthy",
      base=4.0, vol=1.2, floor=-15.0, ceiling=20.0,
      info="Commercial and industrial loan growth - directly funds business investment and payrolls.",
      guide="Rising is favorable - more C&I lending directly funds business investment and payrolls. Falling is unfavorable - businesses losing access to working capital and expansion funding."),
    I("cre-loan-growth", "CRE Loan Growth", "banking_credit_creation", "banking", "banking", "fred", "CREACBW027SBOG", "weekly", "pct_yoy", "higher_is_healthy",
      base=3.0, vol=1.0, floor=-10.0, ceiling=15.0,
      info="Commercial real-estate loan growth - a sector with elevated refinancing risk given the higher-rate environment.",
      guide="Rising is favorable - healthy commercial real estate lending. Falling is unfavorable - CRE is a higher-refinancing-risk sector, so slowing credit here is an early stress signal."),
    I("credit-card-delinquency", "Credit Card Delinquency Rate", "banking_credit_creation", "consumer_credit", "banking", "fred", "DRCCLACBS", "quarterly", "percent", "lower_is_healthy",
      lead_lag="lagging", base=2.5, vol=0.15, floor=1.0, ceiling=8.0,
      info="Delinquency rate on credit card loans at commercial banks. A consumer-stress signal that tends to lag the labor market.",
      guide="Rising is unfavorable - more consumers falling behind on payments signals household financial stress, typically lagging labor-market weakness. Falling is favorable - healthy consumer balance sheets."),
    I("bank-deposit-growth", "Commercial Bank Deposit Growth", "banking_credit_creation", "banking", "banking", "fred", "DPSACBW027SBOG", "weekly", "pct_yoy", "higher_is_healthy",
      base=3.0, vol=1.5, floor=-10.0, ceiling=20.0,
      info="Growth in bank deposits. Sustained outflows can force banks to shrink lending or sell securities at a loss, as seen in the 2023 regional-bank stress episode.",
      guide="Rising is favorable - stable or growing deposits support bank lending capacity. Falling/outflows are unfavorable - can force banks to shrink lending or sell securities at a loss, as in the 2023 regional-bank stress episode."),

    # ---- Liquidity / funding (Section 17) ----
    I("sofr", "SOFR", "liquidity_funding", "repo", "liquidity", "nyfed", "sofr", "daily", "percent", "custom",
      lead_lag="coincident", crisis="high", critical=True, base=5.0, vol=0.03, floor=0.0, ceiling=8.0,
      info="Secured Overnight Financing Rate, the primary reference rate for overnight Treasury-repo funding. Spikes indicate stress in short-term funding markets.",
      guide="A sudden spike is unfavorable - it signals stress or scarcity in overnight funding markets (as in September 2019). Gradual moves mostly track Fed policy and aren't inherently good or bad on their own - compare against the effective fed funds rate for context.",
      source_name="New York Fed"),
    I("sofr-effr-spread", "SOFR minus Effective Fed Funds", "liquidity_funding", "repo", "liquidity", "fred", "N/A_SOFR_EFFR", "daily", "percent", "lower_is_healthy",
      lead_lag="leading", crisis="high", base=0.0, vol=0.02, floor=-0.3, ceiling=1.0,
      info="Gap between repo funding costs and the policy rate. A persistent positive spread signals collateral or reserve scarcity in the repo market.",
      guide="Rising is unfavorable - a persistent positive spread over the policy rate signals collateral or reserve scarcity in repo markets. Falling toward zero is favorable - normal funding-market functioning."),
    I("on-rrp", "ON RRP Balance", "liquidity_funding", "fed_balance_sheet", "liquidity", "fred", "RRPONTSYD", "daily", "usd_billions", "higher_is_healthy",
      crisis="medium", critical=True, base=500.0, vol=40.0, floor=0.0, ceiling=2500.0,
      info="Overnight reverse repo facility usage. A large buffer of ON RRP acts as a liquidity shock absorber; its depletion is watched closely as a net-liquidity signal.",
      guide="A large, stable balance is favorable - it's a liquidity shock absorber. Rapid depletion is unfavorable - it removes that buffer and can foreshadow reserve-scarcity stress once it runs low."),
    I("tga", "Treasury General Account", "liquidity_funding", "fed_balance_sheet", "liquidity", "fred", "WTREGEN", "weekly", "usd_billions", "lower_is_healthy",
      critical=True, base=700.0, vol=60.0, floor=100.0, ceiling=1200.0,
      info="Cash balance the Treasury holds at the Fed. A rising TGA drains reserves from the banking system (tightening); a falling TGA adds reserves (easing).",
      guide="Rising is unfavorable - the Treasury building cash at the Fed drains reserves from the banking system (tightening). Falling is favorable - spending down the TGA adds reserves back into the system (easing)."),
    I("fed-total-assets", "Federal Reserve Total Assets", "liquidity_funding", "fed_balance_sheet", "liquidity", "fred", "WALCL", "weekly", "usd_billions", "higher_is_healthy",
      base=7500.0, vol=30.0, floor=6000.0, ceiling=9000.0,
      info="Size of the Fed's balance sheet. QT (shrinking assets) is a persistent liquidity headwind; QE (growing assets) is a tailwind.",
      guide="Rising is favorable - a growing Fed balance sheet (QE) is a liquidity tailwind for risk assets. Falling is unfavorable - quantitative tightening (QT) is a persistent liquidity headwind."),
    I("bank-reserves", "Bank Reserves", "liquidity_funding", "fed_balance_sheet", "liquidity", "fred", "TOTRESNS", "monthly", "usd_billions", "higher_is_healthy",
      lead_lag="leading", crisis="high", critical=True, base=3200.0, vol=80.0, floor=2500.0, ceiling=4500.0,
      info="Reserve balances held by banks at the Fed. Scarce reserves were the proximate trigger of the September 2019 repo spike.",
      guide="Rising is favorable - ample reserves keep the banking system well-funded. Falling toward scarce levels is unfavorable - reserve scarcity was the proximate trigger of the September 2019 repo spike."),
    I("net-liquidity-proxy", "Net Fed Liquidity Proxy", "liquidity_funding", "fed_balance_sheet", "liquidity", "fred", "N/A_NETLIQ", "weekly", "usd_billions", "higher_is_healthy",
      lead_lag="leading", crisis="high", critical=True, base=6000.0, vol=100.0, floor=4500.0, ceiling=7500.0,
      info="Fed assets minus TGA minus ON RRP - a widely-followed proxy for the liquidity actually available to markets, independent of gross Fed balance-sheet size.",
      guide="Rising is favorable - more liquidity available to markets tends to support risk-asset prices. Falling is unfavorable - a widely-followed proxy for tightening conditions independent of gross Fed balance-sheet size."),
    I("mmf-assets", "Money-Market Fund Assets", "liquidity_funding", "money_markets", "liquidity", "fred", "MMMFFAQ027S", "quarterly", "usd_billions", "custom",
      base=5500.0, vol=50.0, floor=3000.0, ceiling=7500.0,
      info="Total assets in money-market funds. Rising balances can reflect either healthy cash buffers or a defensive flight from risk assets, depending on context.",
      guide="Rising can be either favorable (cash sitting ready to be deployed) or unfavorable (a defensive flight from risk assets) - check equity breadth and credit spreads for context. Falling usually means cash is being redeployed into risk assets."),

    # ---- Equity breadth / internals (Section 8) ----
    I("spx-level", "S&P 500 Level", "equity_breadth_internals", "index", "equity_breadth", "fred", "SP500", "daily", "index", "higher_is_healthy",
      base=5500.0, vol=45.0, drift=0.6, floor=2500.0,
      info="Level of the S&P 500 index.",
      guide="Rising is favorable for the index itself - but check the breadth indicators alongside it, since a rising index with narrowing participation can still be fragile. Falling is unfavorable."),
    I("pct-above-200dma", "% S&P 500 Above 200DMA", "equity_breadth_internals", "breadth", "equity_breadth", "fred", "N/A_PCT200DMA", "daily", "percent", "higher_is_healthy",
      lead_lag="leading", crisis="high", critical=True, base=65.0, vol=6.0, floor=5.0, ceiling=97.0,
      info="Share of S&P 500 constituents trading above their 200-day moving average. A falling reading while the index holds up means fewer stocks are carrying the market.",
      guide="Rising is favorable - more stocks participating in the uptrend is a broad-based, healthy market. Falling while the index holds up is unfavorable - fewer stocks are carrying the market, a classic fragility warning."),
    I("pct-above-50dma", "% S&P 500 Above 50DMA", "equity_breadth_internals", "breadth", "equity_breadth", "fred", "N/A_PCT50DMA", "daily", "percent", "higher_is_healthy",
      base=60.0, vol=10.0, floor=2.0, ceiling=98.0,
      info="Shorter-horizon breadth measure than the 200DMA version; more sensitive to near-term rotation.",
      guide="Rising is favorable - near-term breadth improving. Falling is unfavorable - near-term rotation out of risk, though noisier day-to-day than the 200DMA version."),
    I("new-highs-minus-lows", "New Highs Minus New Lows", "equity_breadth_internals", "breadth", "equity_breadth", "fred", "N/A_NHNL", "daily", "count", "higher_is_healthy",
      critical=True, base=50.0, vol=120.0, floor=-1500.0, ceiling=1500.0,
      info="52-week new highs minus new lows across the exchange. A swing deeply negative even while the index is near highs is a classic breadth-divergence warning.",
      guide="Rising is favorable - more stocks making new highs than new lows signals broad strength. Deeply negative even while the index is near highs is unfavorable - a classic breadth-divergence warning."),
    I("eq-weight-cap-weight", "S&P Equal-Weight / Cap-Weight", "equity_breadth_internals", "breadth", "equity_breadth", "fred", "N/A_RSPvSPY", "daily", "ratio", "higher_is_healthy",
      critical=True, base=1.0, vol=0.008, floor=0.75, ceiling=1.2,
      info="Equal-weight S&P 500 relative to cap-weight. A falling ratio means index gains are concentrated in a handful of mega-caps rather than broad-based.",
      guide="Rising is favorable - gains are broad-based across the index. Falling is unfavorable - index gains are concentrated in a handful of mega-caps rather than the market as a whole."),
    I("russell-vs-sp500", "Small-Cap vs Large-Cap Relative Strength", "equity_breadth_internals", "breadth", "equity_breadth", "fred", "N/A_IWMvSPY", "daily", "ratio", "higher_is_healthy",
      base=1.0, vol=0.01, floor=0.6, ceiling=1.5,
      info="Russell 2000 relative to S&P 500. Small caps are more sensitive to funding costs and domestic growth, so persistent underperformance is a macro-fragility tell.",
      guide="Rising is favorable - small caps, more sensitive to funding costs and domestic growth, participating in gains is a healthy sign. Falling/persistent underperformance is unfavorable - a macro-fragility tell."),
    I("advance-decline", "NYSE Advance/Decline Line", "equity_breadth_internals", "breadth", "equity_breadth", "fred", "N/A_ADLINE", "daily", "index", "higher_is_healthy",
      base=50000.0, vol=400.0, drift=15.0,
      info="Cumulative sum of advancing minus declining issues. A long-running breadth-of-participation gauge.",
      guide="Rising is favorable - more advancing than declining issues reflects broad market participation. Falling is unfavorable - breadth deteriorating even if headline indexes hold up."),

    # ---- Volatility / options (Section 9) ----
    I("vix", "VIX", "volatility_options", "vol", "volatility_options", "cboe", "VIX", "daily", "index", "lower_is_healthy",
      lead_lag="coincident", crisis="high", critical=True, base=16.0, vol=1.4, floor=9.0, ceiling=85.0, cycle=2.0,
      info="CBOE Volatility Index - 30-day implied volatility of S&P 500 options. The most-watched real-time fear gauge; spikes above ~30 have historically coincided with acute stress.",
      guide="Rising is unfavorable - implied volatility spiking reflects rising fear and hedging demand; readings above ~30 have historically coincided with acute stress. Falling is favorable - calm, complacent conditions.",
      source_name="Cboe"),
    I("vix9d", "VIX9D", "volatility_options", "vol", "volatility_options", "cboe", "VIX9D", "daily", "index", "lower_is_healthy",
      base=15.5, vol=1.6, floor=8.0, ceiling=90.0, source_name="Cboe",
      info="9-day VIX. Compared to the 30-day VIX, its slope reveals whether near-term or medium-term fear is more elevated.",
      guide="Rising is unfavorable - near-term fear increasing. Falling is favorable - near-term calm. Compare its slope against the 30-day VIX to see whether near-term or medium-term fear dominates."),
    I("vvix", "VVIX", "volatility_options", "vol_of_vol", "volatility_options", "cboe", "VVIX", "daily", "index", "lower_is_healthy",
      base=95.0, vol=6.0, floor=60.0, ceiling=220.0, source_name="Cboe",
      info="Volatility of the VIX itself. Elevated VVIX alongside a still-moderate VIX can signal building tail-risk hedging demand.",
      guide="Rising is unfavorable - even with VIX still moderate, rising VVIX signals building tail-risk hedging demand beneath the surface. Falling is favorable - stable volatility expectations."),
    I("skew", "CBOE SKEW Index", "volatility_options", "tail_risk", "volatility_options", "cboe", "SKEW", "daily", "index", "lower_is_healthy",
      base=140.0, vol=4.0, floor=110.0, ceiling=175.0, source_name="Cboe",
      info="Measures the market's pricing of tail (crash) risk via out-of-the-money option skew. Higher = more tail-risk hedging demand.",
      guide="Rising is unfavorable - more demand for crash protection via out-of-the-money options. Falling is favorable - less tail-risk hedging demand."),
    I("equity-put-call", "Equity Put/Call Ratio", "volatility_options", "options_flow", "volatility_options", "cboe", "PCE_EQUITY", "daily", "ratio", "custom",
      critical=True, base=0.65, vol=0.08, floor=0.3, ceiling=1.6, source_name="Cboe",
      info="Ratio of equity put volume to call volume. Extremes in either direction can mark sentiment extremes, though it is noisy day-to-day.",
      guide="A high ratio signals fear/hedging demand (can be a contrarian bullish signal at extremes); a low ratio signals complacency/greed (can precede a pullback). Extremes in either direction, not the direction alone, are what matter here."),
    I("realized-vol-20d", "20-Day Realized S&P Volatility", "volatility_options", "realized_vol", "volatility_options", "fred", "N/A_RVOL20", "daily", "percent_ann", "lower_is_healthy",
      base=13.0, vol=1.5, floor=5.0, ceiling=80.0,
      info="Annualized realized volatility of the S&P 500 over the trailing 20 trading days.",
      guide="Rising is unfavorable - actual price swings widening over the past month signals a more turbulent, riskier tape. Falling is favorable - calmer, more orderly price action."),
    I("vix-term-structure", "VIX Futures Term Structure Slope", "volatility_options", "vol", "volatility_options", "cboe", "N/A_VXSLOPE", "daily", "points", "higher_is_healthy",
      critical=True, base=1.2, vol=0.5, floor=-6.0, ceiling=6.0, source_name="Cboe",
      info="Front-month minus spot VIX futures. Positive (contango) is the normal, healthy state; inversion into backwardation signals acute near-term stress.",
      guide="Positive/rising (contango - later-dated futures priced above spot) is the normal, favorable state. Falling into negative (backwardation) is unfavorable - it signals acute near-term stress."),

    # ---- Macro growth (Section 13) ----
    I("gdpnow", "Atlanta Fed GDPNow", "macro_growth", "growth", "growth", "bea", "GDPNOW", "weekly", "pct_saar", "higher_is_healthy",
      lead_lag="leading", crisis="high", critical=True, base=2.2, vol=0.5, floor=-8.0, ceiling=8.0, source_name="Atlanta Fed",
      info="Atlanta Fed's real-time GDP growth nowcast, updated continuously ahead of the official BEA release.",
      guide="Rising is favorable - a strengthening real-time growth read supports earnings expectations. Falling is unfavorable - a weakening nowcast raises recession risk ahead of the official GDP release."),
    I("nyfed-nowcast", "NY Fed Staff Nowcast", "macro_growth", "growth", "growth", "fred", "N/A_NYFEDNOWCAST", "weekly", "pct_saar", "higher_is_healthy",
      lead_lag="leading", crisis="high", critical=True, base=2.0, vol=0.4, floor=-8.0, ceiling=8.0, source_name="New York Fed",
      info="New York Fed's independent GDP nowcast model, a useful cross-check against GDPNow.",
      guide="Rising is favorable - same read as GDPNow from an independent model; use divergence between the two as a confidence check. Falling is unfavorable - a weakening growth nowcast."),
    I("lei", "Conference Board LEI", "macro_growth", "growth", "growth", "fred", "USSLIND", "monthly", "index", "higher_is_healthy",
      lead_lag="leading", crisis="high", critical=True, base=100.0, vol=0.6, floor=85.0, ceiling=115.0,
      info="Composite Leading Economic Index. A sustained multi-month decline has historically preceded most post-war recessions.",
      guide="Rising is favorable - a strengthening leading index supports the growth outlook. Falling, especially a sustained multi-month decline, is unfavorable - it has preceded most post-war recessions."),
    I("ism-mfg-pmi", "ISM Manufacturing PMI", "macro_growth", "growth", "growth", "fred", "MANEMP", "monthly", "index", "higher_is_healthy",
      lead_lag="leading", crisis="high", critical=True, base=50.0, vol=1.8, floor=35.0, ceiling=65.0,
      info="ISM Manufacturing survey. Above 50 = expansion, below 50 = contraction. One of the most timely growth signals available.",
      guide="Rising above 50 (and rising further) is favorable - manufacturing expansion. Falling, especially below 50, is unfavorable - manufacturing contraction."),
    I("ism-services-pmi", "ISM Services PMI", "macro_growth", "growth", "growth", "fred", "N/A_ISMSERV", "monthly", "index", "higher_is_healthy",
      lead_lag="leading", crisis="medium", base=52.0, vol=1.5, floor=38.0, ceiling=65.0,
      info="ISM Services survey - covers the much larger services share of the economy vs. manufacturing.",
      guide="Rising above 50 is favorable - the much larger services economy expanding. Falling below 50 is unfavorable - services contraction."),
    I("industrial-production", "Industrial Production", "macro_growth", "growth", "growth", "fred", "INDPRO", "monthly", "pct_yoy", "higher_is_healthy",
      base=1.5, vol=1.0, floor=-12.0, ceiling=10.0,
      info="Year-over-year growth in industrial output across manufacturing, mining, and utilities.",
      guide="Rising is favorable - factories, mines, and utilities producing more supports growth. Falling is unfavorable - a shrinking industrial base."),
    I("retail-sales", "Retail Sales (Real)", "macro_growth", "growth", "growth", "fred", "RSAFS", "monthly", "pct_yoy", "higher_is_healthy",
      base=2.5, vol=1.2, floor=-15.0, ceiling=15.0,
      info="Inflation-adjusted retail sales growth - a direct read on consumer spending, ~70% of GDP.",
      guide="Rising is favorable - consumer spending (~70% of GDP) holding up. Falling is unfavorable - consumers pulling back, a direct hit to growth."),
    I("housing-starts", "Housing Starts", "macro_growth", "housing", "growth", "fred", "HOUST", "monthly", "thousands_saar", "higher_is_healthy",
      lead_lag="leading", base=1400.0, vol=90.0, floor=600.0, ceiling=2200.0,
      info="New residential construction starts - a classic leading indicator given housing's sensitivity to credit conditions.",
      guide="Rising is favorable - new construction is a classic leading indicator given housing's sensitivity to credit conditions. Falling is unfavorable - often an early sign that tighter credit is biting."),

    # ---- Macro labor (Section 14) ----
    I("unemployment-rate", "Unemployment Rate", "macro_labor", "labor", "labor", "fred", "UNRATE", "monthly", "percent", "lower_is_healthy",
      lead_lag="lagging", crisis="high", critical=True, base=4.0, vol=0.15, floor=3.0, ceiling=12.0,
      info="U-3 headline unemployment rate. Tends to lag the cycle, but sharp increases (see Sahm Rule) are historically decisive recession signals.",
      guide="Rising is unfavorable - this tends to lag the cycle, but sharp increases (see the Sahm Rule) are historically decisive recession signals. Falling is favorable - a tightening labor market."),
    I("initial-claims-4wma", "Initial Claims 4-Week Average", "macro_labor", "labor", "labor", "fred", "IC4WSA", "weekly", "thousands", "lower_is_healthy",
      lead_lag="leading", crisis="high", critical=True, base=220.0, vol=12.0, floor=150.0, ceiling=900.0,
      info="Smoothed weekly initial unemployment claims. One of the most timely labor-market signals available, releasing weekly.",
      guide="Rising is unfavorable - more people newly filing for unemployment, one of the most timely labor signals available. Falling is favorable - layoffs staying contained."),
    I("continuing-claims", "Continuing Claims", "macro_labor", "labor", "labor", "fred", "CCSA", "weekly", "thousands", "lower_is_healthy",
      lead_lag="leading", base=1800.0, vol=60.0, floor=1200.0, ceiling=6000.0,
      info="Number of people continuing to receive unemployment benefits - captures how hard it is to find a new job once laid off.",
      guide="Rising is unfavorable - it's taking longer for laid-off workers to find new jobs. Falling is favorable - a labor market that's still easy to re-enter."),
    I("sahm-rule", "Sahm Rule Indicator", "macro_labor", "labor", "labor", "fred", "SAHMREALTIME", "monthly", "pct_points", "lower_is_healthy",
      lead_lag="leading", crisis="high", critical=True, base=0.15, vol=0.08, floor=-0.3, ceiling=5.0,
      info="3-month average unemployment rate minus its 12-month low. Historically, a reading of 0.50 or higher has reliably signaled recession has already begun.",
      guide="Rising toward 0.50 is unfavorable - historically, crossing that threshold has reliably signaled a recession has already begun. Falling/staying near zero is favorable."),
    I("jolts-openings", "JOLTS Job Openings", "macro_labor", "labor", "labor", "bls", "JTSJOL", "monthly", "millions", "higher_is_healthy",
      base=8.5, vol=0.4, floor=4.0, ceiling=13.0, source_name="BLS",
      info="Total job openings. A sharp drop signals cooling labor demand well before layoffs typically rise.",
      guide="Rising is favorable - strong labor demand. A sharp drop is unfavorable - cooling demand that typically shows up before layoffs rise."),
    I("avg-weekly-hours", "Average Weekly Hours", "macro_labor", "labor", "labor", "fred", "AWHAETP", "monthly", "hours", "higher_is_healthy",
      lead_lag="leading", base=34.3, vol=0.1, floor=33.0, ceiling=35.5,
      info="Average weekly hours worked. Employers typically cut hours before headcount, making this a subtle early-warning signal.",
      guide="Rising is favorable - employers adding hours signals confidence. Falling is unfavorable - employers typically cut hours before headcount, making this a subtle early-warning signal."),
    I("payroll-growth", "Nonfarm Payroll Growth", "macro_labor", "labor", "labor", "fred", "PAYEMS", "monthly", "thousands_mom", "higher_is_healthy",
      base=180.0, vol=60.0, floor=-800.0, ceiling=800.0,
      info="Monthly change in nonfarm payrolls - the headline labor-market print each jobs day.",
      guide="Rising is favorable - solid net hiring each month. Falling, especially negative prints, is unfavorable - outright job losses."),

    # ---- Macro inflation (Section 15) ----
    I("cpi-headline", "CPI Headline", "macro_inflation", "inflation", "inflation", "fred", "CPIAUCSL", "monthly", "pct_yoy", "custom",
      critical=False, base=2.8, vol=0.3, floor=-2.0, ceiling=10.0,
      info="Headline CPI inflation, year-over-year. Not simply 'bad if high' - the dashboard weighs it alongside growth and financial conditions.",
      guide="Not simply good-if-lower: falling inflation alongside stable growth is favorable, but rapidly falling inflation alongside a weakening labor market can itself be a recession warning. Read this alongside the growth and labor indicators, not in isolation."),
    I("core-cpi", "Core CPI", "macro_inflation", "inflation", "inflation", "fred", "CPILFESL", "monthly", "pct_yoy", "custom",
      critical=False, base=3.0, vol=0.25, floor=-1.0, ceiling=8.0,
      info="CPI excluding food and energy - the Fed's preferred near-term read on underlying inflation trend.",
      guide="Same nuance as headline CPI: cooling, well-behaved core inflation with stable growth is favorable (gives the Fed room to ease); a rapid drop alongside weakening growth is a warning sign, not simply good news."),
    I("core-pce", "Core PCE", "macro_inflation", "inflation", "inflation", "fred", "PCEPILFE", "monthly", "pct_yoy", "custom",
      lead_lag="coincident", crisis="medium", critical=True, base=2.7, vol=0.2, floor=-1.0, ceiling=7.0,
      info="Core Personal Consumption Expenditures inflation - the Fed's official target measure.",
      guide="The Fed's official target measure. Cooling toward ~2% with stable growth is favorable; inflation running persistently hot keeps rates higher for longer, which is unfavorable for equity valuations."),
    I("breakeven-5y", "5Y Breakeven Inflation", "macro_inflation", "inflation_expectations", "inflation", "fred", "T5YIE", "daily", "percent", "custom",
      base=2.3, vol=0.05, floor=0.0, ceiling=5.0,
      info="Market-implied 5-year inflation expectations from TIPS vs. nominal Treasuries.",
      guide="Rising expectations can be unfavorable if they force a more hawkish Fed response; well-anchored, stable expectations near target are generally favorable. Sharp moves in either direction are usually more informative than the level."),
    I("wage-growth", "Wage Growth (Avg Hourly Earnings)", "macro_inflation", "inflation", "inflation", "fred", "CES0500000003", "monthly", "pct_yoy", "custom",
      base=4.0, vol=0.3, floor=0.0, ceiling=8.0,
      info="Year-over-year average hourly earnings growth. Persistent wage growth well above productivity + target inflation can keep services inflation sticky.",
      guide="Wage growth well above productivity plus target inflation is unfavorable - it can keep services inflation sticky. Wage growth moderating toward a sustainable pace alongside stable employment is favorable."),

    # ---- Macro fiscal (Section 19) ----
    I("federal-debt-gdp", "Federal Debt / GDP", "macro_fiscal", "fiscal", "rates", "fred", "GFDEGDQ188S", "quarterly", "percent", "lower_is_healthy",
      base=120.0, vol=1.0, floor=60.0, ceiling=160.0,
      info="Total federal debt as a share of GDP. Not itself a timing signal, but relevant context for term-premium and crowding-out risk.",
      guide="Rising raises long-run term-premium and crowding-out risk, though it's a slow-moving structural indicator, not a timing tool. Falling/stabilizing is favorable."),
    I("federal-deficit-gdp", "Federal Deficit / GDP", "macro_fiscal", "fiscal", "rates", "fred", "FYFSGDA188S", "annual", "percent", "higher_is_healthy",
      base=-6.0, vol=0.7, floor=-15.0, ceiling=2.0,
      info="Federal budget balance as a share of GDP (negative = deficit). Large, persistent deficits raise Treasury issuance needs.",
      guide="Rising toward zero (a shrinking deficit) is favorable - less pressure on Treasury issuance. Falling deeper negative (a widening deficit) is unfavorable - larger deficits raise issuance needs and can pressure rates."),
    I("net-interest-expense", "Net Interest Expense (Federal)", "macro_fiscal", "fiscal", "rates", "fred", "A091RC1Q027SBEA", "quarterly", "usd_billions_saar", "lower_is_healthy",
      base=950.0, vol=25.0, floor=200.0, ceiling=1500.0,
      info="Federal net interest expense. Rapid growth here can crowd out other fiscal priorities and pressure long-end Treasury supply/demand.",
      guide="Rising is unfavorable - rapid growth in interest costs can crowd out other fiscal priorities and pressure long-end Treasury supply/demand. Falling/stabilizing is favorable."),
    I("term-premium-proxy", "10Y Term Premium (ACM proxy)", "macro_fiscal", "fiscal", "rates", "fred", "THREEFYTP10", "daily", "percent", "custom",
      base=0.0, vol=0.05, floor=-2.0, ceiling=3.0,
      info="Estimated compensation investors require for duration risk on the 10Y Treasury, beyond expected short-rate policy.",
      guide="Rising can be unfavorable (investors demanding more compensation for duration risk, often alongside fiscal/supply concerns) or can simply reflect a normalizing rate regime - watch it alongside Treasury issuance and auction demand for context."),

    # ---- Macro rates / yield curve (Section 16) ----
    I("dgs10", "10Y Treasury Yield", "macro_rates", "rates", "rates", "treasury", "10 Yr", "daily", "percent", "custom",
      base=4.2, vol=0.05, floor=1.0, ceiling=8.0, source_name="U.S. Treasury",
      info="Benchmark 10-year Treasury yield, the reference rate for mortgages and long-duration equity valuation.",
      guide="Rising yields are unfavorable for equity valuations directly (higher discount rate) but can also reflect stronger growth expectations (favorable); falling yields cut both ways similarly. Read alongside growth data to know which story is driving the move."),
    I("dgs2", "2Y Treasury Yield", "macro_rates", "rates", "rates", "treasury", "2 Yr", "daily", "percent", "custom",
      base=4.0, vol=0.06, floor=0.5, ceiling=8.0, source_name="U.S. Treasury",
      info="2-year Treasury yield - highly sensitive to near-term Fed policy expectations.",
      guide="Highly sensitive to near-term Fed policy expectations - rising typically reflects a more hawkish Fed (unfavorable for valuations); falling reflects expected easing (typically favorable), unless growth is deteriorating sharply."),
    I("dgs3mo", "3M Treasury Yield", "macro_rates", "rates", "rates", "treasury", "3 Mo", "daily", "percent", "custom",
      base=4.5, vol=0.03, floor=0.0, ceiling=7.0, source_name="U.S. Treasury",
      info="3-month T-bill yield, closely tracking the current Fed funds rate.",
      guide="Closely tracks the current Fed funds rate - moves here mostly reflect realized policy, not a standalone equity signal. Use it primarily as the reference point for the yield-curve spread indicators below."),
    I("t10y2y", "10Y-2Y Spread", "macro_rates", "yield_curve", "rates", "fred", "T10Y2Y", "daily", "percent_points", "higher_is_healthy",
      lead_lag="leading", crisis="high", critical=True, base=0.3, vol=0.06, floor=-1.2, ceiling=3.0,
      info="Classic yield-curve inversion signal. Sustained inversion has preceded every U.S. recession since the 1970s, typically with a 6-24 month lead.",
      guide="Rising/steepening (more positive) is favorable - a normal, healthy curve shape. Falling toward or below zero (inverting) is unfavorable - sustained inversion has preceded every U.S. recession since the 1970s."),
    I("t10y3m", "10Y-3M Spread", "macro_rates", "yield_curve", "rates", "fred", "T10Y3M", "daily", "percent_points", "higher_is_healthy",
      lead_lag="leading", crisis="high", critical=True, base=0.0, vol=0.08, floor=-2.0, ceiling=3.0,
      info="The New York Fed's preferred recession-probability curve measure, often considered the cleanest of the curve signals.",
      guide="Rising/steepening is favorable - the NY Fed's preferred recession-probability curve, considered the cleanest of the curve signals. Falling toward or below zero (inverting) is unfavorable - a high-confidence recession warning."),
    I("real-10y-yield", "Real 10Y Yield", "macro_rates", "rates", "rates", "fred", "DFII10", "daily", "percent", "custom",
      lead_lag="leading", critical=True, base=1.8, vol=0.05, floor=-1.5, ceiling=4.0,
      info="10-year TIPS yield - the inflation-adjusted cost of long-duration capital, a key input to equity discount rates.",
      guide="Rising real yields raise the discount rate used in equity valuation models (unfavorable, all else equal) but can also reflect stronger real growth expectations (favorable); falling real yields cut both ways similarly."),

    # ---- Valuation (Section 11) ----
    I("cape", "S&P 500 CAPE Ratio", "valuation", "valuation", "valuation", "fred", "N/A_CAPE", "monthly", "ratio", "custom",
      base=32.0, vol=0.6, floor=10.0, ceiling=45.0,
      info="Shiller cyclically-adjusted P/E. A fragility amplifier, not a timing tool - expensive markets can stay expensive for years absent a liquidity/credit trigger.",
      guide="A fragility amplifier, not a timing tool: elevated and rising isn't itself bearish, but it means a liquidity or credit shock will do more damage than it would at cheaper valuations. Falling from elevated levels reduces (but doesn't eliminate) that fragility."),
    I("trailing-pe", "S&P 500 Trailing P/E", "valuation", "valuation", "valuation", "fred", "N/A_PE", "monthly", "ratio", "custom",
      base=24.0, vol=0.8, floor=10.0, ceiling=40.0,
      info="Trailing twelve-month price-to-earnings ratio for the S&P 500.",
      guide="Same logic as CAPE: rising valuation isn't bad by itself, but it raises the stakes if liquidity or credit conditions deteriorate. Falling reduces valuation-driven fragility."),
    I("earnings-yield-minus-10y", "Earnings Yield minus 10Y", "valuation", "valuation", "valuation", "fred", "N/A_EYMINUS10Y", "monthly", "percent_points", "higher_is_healthy",
      base=0.0, vol=0.15, floor=-4.0, ceiling=5.0,
      info="S&P 500 earnings yield minus the 10Y Treasury yield - a simple equity-risk-premium proxy.",
      guide="Rising is favorable - equities offer more compensation relative to risk-free bonds. Falling is unfavorable - a shrinking equity risk premium, all else equal."),
    I("market-cap-gdp", "Market Cap / GDP", "valuation", "valuation", "valuation", "fred", "N/A_BUFFETT", "quarterly", "percent", "custom",
      base=190.0, vol=4.0, floor=60.0, ceiling=230.0,
      info="Total U.S. equity market cap relative to GDP - the 'Buffett Indicator'. A long-horizon valuation gauge, not a timing tool.",
      guide="A long-horizon valuation gauge (the 'Buffett Indicator'), not a timing tool. Elevated and rising raises long-run fragility; it says little about near-term direction on its own."),
    I("mega-cap-concentration", "Mega-Cap Concentration (Top 10 %)", "valuation", "concentration", "valuation", "fred", "N/A_TOP10", "monthly", "percent", "lower_is_healthy",
      critical=True, base=38.0, vol=1.0, floor=15.0, ceiling=45.0,
      info="Share of S&P 500 market cap held by the 10 largest constituents. Extreme concentration raises idiosyncratic and breadth-fragility risk.",
      guide="Rising is unfavorable - more of the index's fate riding on fewer stocks raises idiosyncratic and breadth-fragility risk. Falling (more broadly distributed market cap) is favorable."),

    # ---- Sentiment / positioning (Section 12) ----
    I("aaii-spread", "AAII Bull-Bear Spread", "sentiment_positioning", "sentiment", "sentiment_positioning", "fred", "N/A_AAII", "weekly", "percent_points", "custom",
      base=5.0, vol=12.0, floor=-50.0, ceiling=50.0,
      info="AAII individual-investor bullish minus bearish percentage. A contrarian sentiment gauge - useful in context, noisy in isolation.",
      guide="A contrarian gauge: extreme bullishness (high positive spread) has historically preceded weaker forward returns, and extreme bearishness has often preceded rallies. Extremes, not the level itself, are what matter."),
    I("put-call-sentiment", "Put/Call Sentiment Composite", "sentiment_positioning", "sentiment", "sentiment_positioning", "cboe", "N/A_PCSENT", "daily", "index", "custom",
      base=50.0, vol=8.0, floor=0.0, ceiling=100.0, source_name="Cboe",
      info="Composite sentiment reading built from options put/call flow.",
      guide="Extremes in either direction - very high (fear) or very low (complacency/greed) - raise the odds of a reversal. Moderate, middling readings are the 'normal' state."),
    I("margin-debt-mktcap", "Margin Debt / Market Cap", "sentiment_positioning", "positioning", "sentiment_positioning", "finra", "N/A_MARGIN", "monthly", "percent", "lower_is_healthy",
      crisis="medium", base=1.7, vol=0.08, floor=0.8, ceiling=3.0, source_name="FINRA",
      info="FINRA margin debt relative to total market cap. Elevated and rising leverage increases the risk of forced-selling cascades in a drawdown.",
      guide="Rising is unfavorable - elevated and rising leverage increases the risk of forced-selling cascades in a drawdown. Falling is favorable - deleveraging reduces that tail risk."),
    I("equity-fund-flows", "Equity Fund Flows", "sentiment_positioning", "flows", "sentiment_positioning", "fred", "N/A_EQFLOWS", "weekly", "usd_billions", "higher_is_healthy",
      base=2.0, vol=8.0, floor=-60.0, ceiling=60.0,
      info="Net flows into equity mutual funds and ETFs. Sustained outflows even during price stability can be an early positioning-risk signal.",
      guide="Rising/positive inflows are favorable - capital being deployed into equities. Sustained outflows are unfavorable, even during price stability - an early positioning-risk signal."),
    I("cftc-spx-positioning", "CFTC S&P Futures Positioning", "sentiment_positioning", "positioning", "sentiment_positioning", "cftc", "N/A_CFTC_SPX", "weekly", "net_contracts", "custom",
      base=0.0, vol=40000.0, floor=-300000.0, ceiling=300000.0, source_name="CFTC",
      info="Net speculative positioning in S&P 500 futures from the CFTC Commitments of Traders report. Crowded positioning raises reversal risk.",
      guide="Extremely crowded positioning in either direction (very long or very short) raises reversal risk, since a sharp move can force fast unwinds. Moderate, balanced positioning is the lower-risk state."),

    # ---- Global liquidity / FX (Section 20) ----
    I("bis-usd-credit-growth", "BIS Global USD Credit Growth", "global_liquidity", "global_liquidity", "global_fx_liquidity", "bis", "N/A_BISUSD", "quarterly", "pct_yoy", "higher_is_healthy",
      lead_lag="leading", crisis="high", critical=True, base=4.0, vol=1.2, floor=-10.0, ceiling=15.0, source_name="BIS",
      info="BIS's global liquidity indicator for USD-denominated credit to non-bank borrowers outside the U.S. A top-tier global funding-conditions gauge.",
      guide="Rising/accelerating growth is generally favorable - it reflects easier global USD funding conditions. But excessive acceleration can also signal a credit bubble building, so treat sustained sharp acceleration as a caution flag, not an unambiguous positive."),
    I("global-m2-proxy", "Global M2 Growth Proxy", "global_liquidity", "global_liquidity", "global_fx_liquidity", "bis", "N/A_GM2", "monthly", "pct_yoy", "higher_is_healthy",
      base=5.0, vol=1.5, floor=-8.0, ceiling=20.0, source_name="BIS",
      info="Aggregate money-supply growth across major economies - a coarse global liquidity backdrop indicator.",
      guide="Rising is favorable - expanding global money supply is a supportive liquidity backdrop. Falling is unfavorable - tightening global liquidity."),
    I("central-bank-bs-aggregate", "G4 Central Bank Balance Sheet Aggregate", "global_liquidity", "global_liquidity", "global_fx_liquidity", "bis", "N/A_G4CB", "monthly", "usd_trillions", "higher_is_healthy",
      base=20.0, vol=0.3, floor=14.0, ceiling=26.0, source_name="BIS",
      info="Combined Fed/ECB/BOJ/PBOC balance-sheet size - the broadest available proxy for global central-bank liquidity provision.",
      guide="Rising is favorable - major central banks collectively adding liquidity. Falling is unfavorable - collective global central-bank tightening."),
    I("dxy", "DXY / Broad Dollar Index", "global_fx", "fx", "global_fx_liquidity", "fred", "DTWEXBGS", "daily", "index", "lower_is_healthy",
      lead_lag="leading", crisis="high", critical=True, base=104.0, vol=0.5, floor=85.0, ceiling=125.0,
      info="Trade-weighted broad dollar index. A rapidly strengthening dollar tightens financial conditions globally, especially for dollar-denominated borrowers.",
      guide="Rising is typically unfavorable - a rapidly strengthening dollar tightens financial conditions globally, especially for dollar-denominated borrowers. Falling is typically favorable - easier global conditions, though a very weak dollar can also reflect capital flight from U.S. assets."),
    I("eurusd", "EUR/USD", "global_fx", "fx", "global_fx_liquidity", "fred", "DEXUSEU", "daily", "rate", "higher_is_healthy",
      base=1.08, vol=0.006, floor=0.9, ceiling=1.3,
      info="Euro/dollar exchange rate, the most heavily-traded currency pair and a proxy for relative U.S./European conditions.",
      guide="Rising is favorable - a weaker dollar eases global financial conditions, mirroring a falling DXY. Falling (dollar strength) is unfavorable - it shares the same tightening implications as a rising DXY."),
    I("usdjpy", "USD/JPY", "global_fx", "fx", "global_fx_liquidity", "fred", "DEXJPUS", "daily", "rate", "custom",
      base=150.0, vol=1.2, floor=100.0, ceiling=170.0,
      info="Dollar/yen exchange rate. Sharp moves here can trigger unwinds of the JPY carry trade, a known source of cross-asset volatility.",
      guide="Sharp, fast moves in either direction are the concern - they can trigger unwinds of the JPY carry trade, a known source of cross-asset volatility. A stable, gradual trend is the lower-risk state."),
    I("em-fx-index", "EM FX Index (proxy)", "global_fx", "fx", "global_fx_liquidity", "bis", "N/A_EMFX", "daily", "index", "higher_is_healthy",
      base=100.0, vol=0.6, floor=70.0, ceiling=115.0, source_name="BIS",
      info="Composite emerging-market currency index. EM FX weakness often signals broader global dollar-funding stress.",
      guide="Rising is favorable - stronger emerging-market currencies reflect healthy global dollar-funding conditions. Falling is unfavorable - EM FX weakness often signals broader global dollar-funding stress."),

    # ---- Global growth (Section 20) ----
    I("global-composite-pmi", "Global Composite PMI", "global_growth", "global_growth", "growth", "bea", "N/A_GCOMPMI", "monthly", "index", "higher_is_healthy",
      lead_lag="leading", base=51.0, vol=1.2, floor=42.0, ceiling=60.0, source_name="OECD",
      info="Global composite (manufacturing + services) PMI - the broadest single read on world growth momentum.",
      guide="Rising above 50 (and rising further) is favorable - broad global growth momentum. Falling, especially below 50, is unfavorable - global growth contracting."),
    I("china-industrial-production", "China Industrial Production", "global_growth", "china", "growth", "bea", "N/A_CHINAIP", "monthly", "pct_yoy", "higher_is_healthy",
      base=5.5, vol=1.5, floor=-5.0, ceiling=18.0, source_name="World Bank",
      info="China industrial production growth - a proxy for global manufacturing and commodity demand given China's share of world industrial activity.",
      guide="Rising is favorable - stronger Chinese output supports global manufacturing and commodity demand. Falling is unfavorable, given China's outsized share of world industrial activity."),
    I("eurozone-pmi", "Eurozone Composite PMI", "global_growth", "europe", "growth", "bea", "N/A_EZPMI", "monthly", "index", "higher_is_healthy",
      base=50.0, vol=1.3, floor=40.0, ceiling=60.0, source_name="OECD",
      info="Eurozone composite PMI, the leading real-time growth gauge for the euro area.",
      guide="Rising above 50 is favorable - euro-area expansion. Falling below 50 is unfavorable - euro-area contraction."),
    I("japan-industrial-production", "Japan Industrial Production", "global_growth", "japan", "growth", "bea", "N/A_JPIP", "monthly", "pct_yoy", "higher_is_healthy",
      base=1.0, vol=2.0, floor=-15.0, ceiling=12.0, source_name="OECD",
      info="Japan industrial production growth, year-over-year.",
      guide="Rising is favorable - Japanese output growth. Falling is unfavorable - contracting output."),

    # ---- Global inflation / rates (Section 20) ----
    I("global-10y-yields-proxy", "Global 10Y Sovereign Yields (proxy)", "global_inflation_rates", "global_rates", "rates", "fred", "IRLTLT01OECDM156N", "monthly", "percent", "custom",
      base=3.2, vol=0.15, floor=0.0, ceiling=7.0,
      info="OECD-average 10-year government bond yield - a broad global rate backdrop measure.",
      guide="Rising global yields raise discount rates worldwide (unfavorable, all else equal) but can also reflect stronger global growth (favorable) - the same growth-vs-rates tension as U.S. Treasury yields."),
    I("eurozone-inflation", "Eurozone Inflation", "global_inflation_rates", "global_inflation", "rates", "fred", "CP0000EZ19M086NEST", "monthly", "pct_yoy", "custom",
      base=2.4, vol=0.3, floor=-2.0, ceiling=10.0,
      info="Eurozone HICP inflation, year-over-year.",
      guide="Similar nuance to U.S. inflation: cooling toward target with stable growth is favorable; a rapid drop alongside weakening euro-area growth is a warning sign, not simply good news."),

    # ---- Global equities (Section 21) ----
    I("msci-world", "MSCI World Proxy", "global_equities", "developed", "equity_breadth", "fred", "N/A_MSCIWORLD", "daily", "index", "higher_is_healthy",
      base=3400.0, vol=25.0, drift=0.4, floor=1800.0,
      info="Broad developed-market equity index proxy.",
      guide="Rising is favorable - broad developed-market strength. Falling is unfavorable - global developed-market weakness."),
    I("msci-em", "MSCI Emerging Markets Proxy", "global_equities", "emerging", "equity_breadth", "fred", "N/A_MSCIEM", "daily", "index", "higher_is_healthy",
      base=1050.0, vol=14.0, floor=600.0,
      info="Broad emerging-market equity index proxy.",
      guide="Rising is favorable - emerging-market risk appetite improving. Falling is unfavorable - EM weakness, often an early global-stress signal."),
    I("europe-equities", "Europe Equities", "global_equities", "europe", "equity_breadth", "fred", "N/A_EUROPE", "daily", "index", "higher_is_healthy",
      base=500.0, vol=5.0, floor=300.0,
      info="Broad European equity index proxy.",
      guide="Rising is favorable - European equity strength. Falling is unfavorable - European weakness."),
    I("japan-equities", "Japan Equities", "global_equities", "japan", "equity_breadth", "fred", "N/A_JAPAN", "daily", "index", "higher_is_healthy",
      base=39000.0, vol=400.0, floor=20000.0,
      info="Broad Japanese equity index proxy (Nikkei-style).",
      guide="Rising is favorable - Japanese equity strength. Falling is unfavorable - Japanese weakness."),
    I("china-equities", "China Equities", "global_equities", "china", "equity_breadth", "fred", "N/A_CHINA", "daily", "index", "higher_is_healthy",
      base=3000.0, vol=40.0, floor=1800.0,
      info="Broad China onshore/offshore equity index proxy.",
      guide="Rising is favorable - Chinese equity strength. Falling is unfavorable - Chinese weakness, historically a source of global contagion risk."),
    I("pct-regions-below-200dma", "% Major Regions Below 200DMA", "global_equities", "contagion", "equity_breadth", "fred", "N/A_REGIONS200DMA", "daily", "percent", "lower_is_healthy",
      lead_lag="leading", crisis="high", critical=True, base=25.0, vol=12.0, floor=0.0, ceiling=100.0,
      info="Simple but powerful contagion indicator: the share of tracked major equity regions trading below their 200-day moving average.",
      guide="Rising is unfavorable - more global regions breaking down technically raises the odds U.S. equities aren't immune to the same pressures. Falling is favorable - broadening global technical strength."),

    # ---- Global commodities (Section 22) ----
    I("wti-crude", "WTI Crude", "global_commodities", "energy", "growth", "fred", "DCOILWTICO", "daily", "usd_per_bbl", "custom",
      base=75.0, vol=1.5, floor=20.0, ceiling=150.0,
      info="WTI crude oil price. A real-economy demand signal and a direct input to headline inflation.",
      guide="Rising can be unfavorable (a direct input to headline inflation, a tax on consumers) or favorable (reflecting stronger real-economy demand) depending on the driver; falling similarly cuts both ways - check whether it's a demand or supply story."),
    I("copper", "Copper", "global_commodities", "industrial_metals", "growth", "fred", "PCOPPUSDM", "monthly", "usd_per_lb", "higher_is_healthy",
      lead_lag="leading", base=4.2, vol=0.15, floor=1.5, ceiling=6.0,
      info="Copper price - 'Dr. Copper', a classic industrial-demand and global-growth bellwether.",
      guide="Rising is generally favorable - 'Dr. Copper' rising reflects strengthening industrial demand and global growth. Falling is generally unfavorable - weakening industrial demand, though supply-side moves can also drive the price."),
    I("copper-gold-ratio", "Copper/Gold Ratio", "global_commodities", "regime", "growth", "fred", "N/A_COPPERGOLD", "daily", "ratio", "higher_is_healthy",
      lead_lag="leading", base=0.18, vol=0.006, floor=0.08, ceiling=0.3,
      info="Copper priced in gold - a regime indicator for growth/risk-on vs. defensive/risk-off conditions. Useful in context; should never override direct credit/liquidity data.",
      guide="Rising is favorable - a regime shift toward growth/risk-on. Falling is unfavorable - a shift toward defensive/risk-off positioning. Useful for regime context; should never override direct credit/liquidity data."),
    I("gold", "Gold", "global_commodities", "safe_haven", "growth", "fred", "N/A_GOLD", "daily", "usd_per_oz", "custom",
      base=2450.0, vol=25.0, drift=0.5, floor=1200.0,
      info="Gold price. A traditional safe-haven and inflation-hedge asset; sharp rallies can reflect either inflation concern or flight-to-safety.",
      guide="Rising can reflect either inflation concern or flight-to-safety demand - check whether equities are also selling off (safety) or whether it's an inflation story. Falling typically reflects reduced safe-haven/inflation-hedge demand."),

    # ---- AI / semiconductor demand (Section 27) ----
    I("semi-sales-yoy", "Global Semiconductor Sales YoY", "ai_demand", "demand", "ai_semiconductor", "sia_wsts", "N/A_SIASALES", "monthly", "pct_yoy", "higher_is_healthy",
      lead_lag="leading", crisis="medium", critical=True, base=12.0, vol=6.0, floor=-25.0, ceiling=45.0, source_name="SIA/WSTS",
      info="SIA/WSTS global semiconductor sales growth, year-over-year - the highest-level demand signal for the whole AI/semi supply chain.",
      guide="Rising is favorable - accelerating chip sales is the highest-level demand signal for the whole AI/semi supply chain. Falling is unfavorable - decelerating end demand."),
    I("semi-etf-relative-strength", "Semiconductor ETF Relative Strength", "ai_demand", "demand", "ai_semiconductor", "fred", "N/A_SMHvSPY", "daily", "ratio", "higher_is_healthy",
      base=1.0, vol=0.015, floor=0.5, ceiling=1.8,
      info="Semiconductor sector ETF performance relative to the S&P 500 - the market's real-time read on sector demand expectations.",
      guide="Rising is favorable - the market pricing in stronger sector demand expectations. Falling is unfavorable - the market pricing in weaker demand or rising sector-specific risk."),
    I("hyperscaler-capex-growth", "Hyperscaler Capex Growth", "ai_demand", "hyperscaler", "ai_semiconductor", "sec", "N/A_HYPCAPEX", "quarterly", "pct_yoy", "higher_is_healthy",
      critical=True, base=35.0, vol=8.0, floor=-10.0, ceiling=80.0, source_name="SEC filings",
      info="Aggregate capex growth across the largest AI-infrastructure hyperscaler buyers - the demand engine at the top of the AI supply chain.",
      guide="Rising capex is favorable for near-term semiconductor/AI-infrastructure revenue, but very rapid acceleration outrunning hyperscaler free cash flow (see the FCF trend indicator) raises overinvestment/funding risk. Falling capex growth is unfavorable for AI suppliers' near-term revenue."),

    # ---- AI / semiconductor funding stress (Section 28) ----
    I("hyperscaler-net-debt-trend", "Hyperscaler Net Debt Trend", "ai_funding", "hyperscaler", "ai_semiconductor", "sec", "N/A_HYPNETDEBT", "quarterly", "pct_yoy", "lower_is_healthy",
      critical=True, base=8.0, vol=6.0, floor=-20.0, ceiling=60.0, source_name="SEC filings",
      info="Growth in net debt across major AI hyperscalers. Rising net debt funding capex faster than FCF can support is an early funding-stress signal.",
      guide="Rising is unfavorable - debt growing faster than free cash flow can support is an early funding-stress signal. Falling/stable is favorable - capex being funded without excessive leverage."),
    I("hyperscaler-fcf-trend", "Hyperscaler FCF Trend", "ai_funding", "hyperscaler", "ai_semiconductor", "sec", "N/A_HYPFCF", "quarterly", "pct_yoy", "higher_is_healthy",
      critical=True, base=5.0, vol=10.0, floor=-40.0, ceiling=40.0, source_name="SEC filings",
      info="Free-cash-flow growth across major AI hyperscalers. When FCF growth trails capex growth for several quarters, funding stress risk rises.",
      guide="Rising is favorable - strong free-cash-flow growth means capex is self-funded. Falling, especially trailing capex growth for several quarters, is unfavorable - funding stress risk rising."),
    I("ai-supplier-debt-growth", "AI Supplier Debt Growth", "ai_funding", "suppliers", "ai_semiconductor", "sec", "N/A_SUPDEBT", "quarterly", "pct_yoy", "lower_is_healthy",
      base=6.0, vol=5.0, floor=-15.0, ceiling=45.0, source_name="SEC filings",
      info="Debt growth across the AI supply-chain (networking/infrastructure) companies tracked by the Company Monitor.",
      guide="Rising is unfavorable - AI supply-chain companies taking on debt faster raises balance-sheet risk. Falling/stable is favorable."),
    I("ai-supplier-cash-debt", "AI Supplier Cash / Debt", "ai_funding", "suppliers", "ai_semiconductor", "sec", "N/A_SUPCASHDEBT", "quarterly", "ratio", "higher_is_healthy",
      base=1.1, vol=0.15, floor=0.2, ceiling=4.0, source_name="SEC filings",
      info="Aggregate cash-to-debt ratio across AI supply-chain companies - a simple liquidity-cushion gauge.",
      guide="Rising is favorable - a stronger liquidity cushion relative to debt. Falling is unfavorable - a thinner cushion, less room to absorb a downturn."),
]
